new Vue({
  el: "#app",
  data: {
    items: {
      park: [
        { name: "Bikes", image: "quadpod.png" },
        { name: "Playground", image: "quadpod.png" },
        { name: "Trashcan", image: "quadpod.png" },
        { name: "Wanamaker Oak", image: "" },
        { name: "Park Center sign ", image: "" },
        { name: "Vollyball net", image: "" },
        { name: "Sprinkeler", image: "" },
        { name: "Map sign", image: "" },
        { name: "Grill", image: "" },
        { name: "Magnolia shelter", image: "" },
        { name: "Picnic table", image: "" },
        { name: "Boat", image: "" },
        { name: "Bench", image: "" },
        { name: "Dimond trail sign", image: "" },
        { name: "Pavillon", image: "" },
        { name: "Restrooms", image: "" },
        { name: "Big hill", image: "" },
      ], // <-- don't delete this!
      nature: [
        { name: "Bird (Cardinal, falcon, etc.)", image: "" },
        { name: "Fallen tree", image: "" },
        { name: "Spider (Banana spider, black widow, etc.)", image: "" },
        { name: "Reptile (Turtle, alligator, etc.)", image: "" },
        { name: "Mammal (Deer, raccoon, etc.)" },
        { name: "Creek or lake", image: "" },
        { name: "Hole in a tree", image: "" },
        { name: "Split tree", image: "" },
        { name: "Tree vine", image: "" },
        { name: "Spanish moss", image: "" },
        { name: "Bird's nest", image: "" },
        { name: "Insect (Dragon fly, mosquitoe, etc.)", image: "" },
        { name: "Algea", image: "" },
        { name: "Tree", image: "" },
        { name: "Rock", image: "" },
        { name: "Cyprus knees", image: "" },
        { name: "Tree stump", image: "" },
      ],
    },
  },
});
