new Vue({
  el: "#app",
  data: {
    items: {
      park: [
        { name: "Bikes", image: "IMG_5618.JPG" },
        { name: "Playground", image: "IMG_5628.JPG" },
        { name: "Trashcan", image: "" },
        { name: "Wanamaker Oak", image: "IMG_5442.JPG" },
        { name: "Park Center sign ", image: "IMG_5619.JPG" },
        { name: "Vollyball net", image: "IMG_5603.JPG" },
        { name: "Sprinkler", image: "" },
        { name: "Map sign", image: "IMG_5544.JPG" },
        { name: "Grill", image: "" },
        { name: "Magnolia shelter", image: "" },
        { name: "Picnic table", image: "" },
        { name: "Boat", image: "IMG_5445.JPG" },
        { name: "Bench", image: "IMG_5566.JPG" },
        { name: "Dimond trail sign (any color)", image: "IMG_5559.JPG" },
        { name: "Pavillon", image: "IMG_5606.JPG" },
        { name: "Restrooms", image: "IMG_5613.JPG" },
        { name: "Big hill", image: "IMG_5630.JPG" },
        { name: "Cypress Hall", image: "IMG_5597.JPG" },
        { name: "Bench swing", image: "IMG_5617.JPG" },
      ], // <-- don't delete this!
      nature: [
        { name: "Bird (cardinal, falcon, etc.)", image: "" },
        { name: "Fallen tree", image: "IMG_5535.JPG" },
        { name: "Spider (banana spider, black widow, etc.)", image: "IMG_5632.JPG" },
        { name: "Reptile (turtle, alligator, etc.)", image: "" },
        { name: "Mammal (deer, raccoon, etc.)" },
        { name: "Creek", image: "IMG_5501.JPG" },
        { name: "Hole in a tree", image: "IMG_5553.JPG" },
        { name: "Split tree", image: "IMG_5538.JPG" },
        { name: "Tree vine", image: "" },
        { name: "Spanish moss", image: "IMG_5503.JPG" },
        { name: "Bird's nest", image: "" },
        { name: "Insect (dragonfly, mosquito, etc.)", image: "IMG_5438.JPG" },
        { name: "Algea", image: "" },
        { name: "Tree", image: "IMG_5591.JPG" },
        { name: "Rock", image: "IMG_5578.JPG" },
        { name: "Cyprus knees", image: "IMG_5571.JPG" },
        { name: "Tree stump", image: "IMG_5574.JPG" },
        { name: "Lake", image: "IMG_5615.JPG" },
      ],
    },
  },
});
